### ISSUE TITLE
VLC Not Starting

### ISSUE THREAD

**Issue by jsmith0103** [hcgonzalezpr/PIzeroKaraoke#1]
I have the web server up and running, a test .mp3 in the correct directory, logging in to CL...but when I try to play or queue the song nothing happens. Any ideas?

**Comment by trbail01** [comment]
I can help you out with this! Make sure you have VLC installed (sorry, I'm assuming you do). Once it's installed, you should be able to sign into your Raspberry Pi and execute the following command to startup VLC: `/usr/bin/cvlc -A alsa -f --intf http --http-host 0.0.0.0 --http-port 8080 --http-password 'vlc' --no-osd -V fb --no-fb-tty --fbdev /dev/fb0 --swscale-mode 4 /home/pi/bg.jpg -q`

If you want this to automatically startup when you turn on your Raspberry Pi, then add the CVLC Service that @hcgonzalezpr kindly provided for us.

I stumbled a little getting the CVLC Service added, so please don't hesitate to reach back out for help with that or - if my reply doesn't seem to be working for you.

**Comment by hcgonzalezpr** [comment]
@trbail01 You are correct thanks for awesome the explanation :)

@jsmith0103 is recommended you run your rpi in text mode and run VLC using startup script

**Comment by jsmith0103** [comment]
Thank you both for your replies! It appears that I also erred in setting up the CVLC service - can you provide some guidance? I’m running the latest version of Stretch. Alternatively, would pasting the command you provided above into fstab work?

**Comment by trbail01** [comment]
@jsmith0103 - There's no need to change anything in the fstab file. This file is for mounting filesystems at system startup. Here is what you are needing to do in order to enable the service.

Copy the cvlc.service file to the `/etc/systemd/system` directory. Then run the command `sudo systemctl enable cvlc.service` which will cause the service to start automatically between system reboots. Finally, start-up the service by typing in `sudo systemctl start cvlc.service`. Take a look at the screenshot below for an example. Let me know if you are still having any issues.
![enable cvlc service pizerokaraoke](https://user-images.githubusercontent.com/9650898/38225254-af947e5e-36b9-11e8-82ee-b587aaa8cb29.png)

**Comment by jsmith0103** [comment]
I’ve been able to verify that cvlc.service is enabled and started (although it appears to be running /usr/bin/vlc as opposed to cvlc), however attempting to play or queue a song still leads to Now Performing: Null and Current Queue: 0 on the web page. I noticed in the command you provided, you specify http port 8080 however my server is on port 80 - could this be part of the issue? When I try port 8080 I’m prompted for a login/password - what would these be?

**Comment by trbail01** [comment]
Please verify that your system is starting VLC in fullscreen mode. It should display the image you have under `/home/pi/bg.jpg`.

**Comment by jsmith0103** [comment]
The big.jpg image briefly displays on startup, however then it goes back to a black terminal screen. Running the command you provided in your first comment does the same thing - be.jpg appears for a few seconds, then just a black screen. Trying to use the webpage still shows Now Performing: Null and Current Queue: 0.

**Comment by jsmith0103** [comment]
That should be bg.jpg above.

**Comment by hcgonzalezpr** [comment]
@jsmith0103 it will still show Now Performing: Null, that code has not implemented, they way to check that it works, is to go into search and see the number of listed songs.

Port 8080 is the port where VLC is going to be running its back end process.
Port 80 is the port of the web interface for the user.

To verify whats happening you can use Chrome and hit Crtl+Shift+I and go to the Network tab.
Retry selecting a new song and it should show a new request.

**Comment by trbail01** [comment]
@jsmith0103 - Just as @hcgonzalezpr mentioned; open up the Developer tools in Chrome and see what's happening when you try to play a song.
![open developer tools chrome](https://user-images.githubusercontent.com/9650898/38261260-54c54988-372f-11e8-90f9-a54e61b14ba9.png)

Make sure you're not getting any errors in the console (see my screen shot example of an error). Make sure you have no 404 missing files when trying to play a song.
![pikaraoke error](https://user-images.githubusercontent.com/9650898/38261300-7100444a-372f-11e8-92b9-c98bb313506f.png)
You mention that the background image goes away or only displays for a brief moment. This is normal behavior. Maybe there's a way to keep it up constantly but i'm not sure. Please share how to accomplish this if you know of a way. 

One thing you could try is copying the .bash_profile file into `/home/pi/.bash_profile`. This will cause VLC to open up each time you sign in with your pi account. See my quick video example:
https://youtu.be/nci9HfhdrP4

**Comment by hcgonzalezpr** [comment]
@trbail01 Awesome documentation :) 

Want me to add you collaborator so a better wiki can be built, I got a couple more tweaks that will fix a couple glitches like the blinking cursor on the corner, but i'm pretty bad at documenting.

**Comment by trbail01** [comment]
That would be great! I'd be glad to add more documentation!

**Comment by hcgonzalezpr** [comment]
@trbail01 you should be able to edit the Wiki now.

**Comment by jsmith0103** [comment]
Thank you both again for all of your help! I’m now at the point where the music is playing, however VLC doesn’t seem to be reading the .lrc file and all I see is a black screen with cursor flashing in the lower left corner while the song is playing. Is .mp3/.lrc the correct format for this? Or do I need an audio/video file of some sort?

**Comment by hcgonzalezpr** [comment]
I'm not sure if VLC supports .lrc , the formar I have everything configured to run its .mp3/.cdg

Both the .mp3/.cdg should be named the same

**Comment by worldofvaldeezy** [comment]
Omg all these comments helped so much lol!!! I was having trouble getting the software side of things working as im kinda new to this stuff! Thanks!

**Comment by jsmith0103** [comment]
Everything is working great - thank you again for all of your help!
